// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "hub-20190121171736-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://hub-20190121171736-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:a52af2b9-65e9-446e-8629-e616dc80e4e9",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_E3gdtkgo9",
    "aws_user_pools_web_client_id": "62unvpi1ca6h7374vp8momods0",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "messages",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apicceee9ce",
            "endpoint": "https://5kesfd5ta0.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
